spring.datasource:
  #url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  #username: sa
  #password: sa
#spring.h2.console.enabled: true
 driverClassName: com.mysql.jdbc.Driver
 url: jdbc:mysql://mysql:3306/boamay2022camundadb?useSSL=true&nullCatalogMeansCurrent=true 
 username: root
 password: password
spring.jpa.hibernate.ddl-auto: update

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
#  default-serialization-format: application/json
server.port: 6064
orderUrl: http://localhost:7070/orders/v1.0
spring.application.name: Ecommerce-API
management.endpoint.metrics.enabled: true
management.endpoints.web.exposure.include: all
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true

